# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ManagedKubernetesAuditingToolkit < Formula
  desc ""
  homepage "https://github.com/DataDog/managed-kubernetes-auditing-toolkit"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/managed-kubernetes-auditing-toolkit/releases/download/v0.1.0/managed-kubernetes-auditing-toolkit_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "752ef31cd32201e1e7af3ca42973804377c5e707edb02492ba334c9fbf8b7f3c"

      def install
        bin.install "mkat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DataDog/managed-kubernetes-auditing-toolkit/releases/download/v0.1.0/managed-kubernetes-auditing-toolkit_0.1.0_Darwin_arm64.tar.gz"
      sha256 "b7288b0229c2408e10a63c78cbc708519c375a32509611624da00822a658238b"

      def install
        bin.install "mkat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/managed-kubernetes-auditing-toolkit/releases/download/v0.1.0/managed-kubernetes-auditing-toolkit_0.1.0_Linux_arm64.tar.gz"
      sha256 "952c833d24888edac781e5eb04a3416c23b5f8729cc0e9933f81875c1b6e39e6"

      def install
        bin.install "mkat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/managed-kubernetes-auditing-toolkit/releases/download/v0.1.0/managed-kubernetes-auditing-toolkit_0.1.0_Linux_x86_64.tar.gz"
      sha256 "224627693d85ad84f72683a7d6888cd564a4ba5fb9f949cb68a70dcab835af99"

      def install
        bin.install "mkat"
      end
    end
  end
end
