name: release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to federate tokens for dd-octo-sts
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.19
      - uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        id: octo-sts
        with:
          scope: DataDog/managed-kubernetes-auditing-toolkit
          policy: self.release.create-pr
      - name: Run GoReleaser
        timeout-minutes: 60
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
