name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write
  
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.19
      - name: Run GoReleaser
        timeout-minutes: 60
        uses: goreleaser/goreleaser-action@v3.2.0
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --config .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
