name: "go static analysis"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    name: "Run Go static analysis"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: "2024.1"
        install-go: false
