name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Set up Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: 1.18

      - name: Run unit tests
        run: make test
